version: '3'
services:
  exp-app:
    image: node:15-alpine3.10
    container_name: ex-app
    working_dir: /src
    ports:
      - 80:3000
    volumes:
      - ./express-app:/src
    environment: 
      NODE_ENV: development
    command: [sh, -c, npm install && npm start]

  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./mongo-db/db:/data/db
      - ./mongo-db/configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  