version: '3'
services:
  web:
#    build:
#      context: .
#      dockerfile: ./node/Dockerfile
    image: node:15-alpine3.10
    container_name: 'front-react-app'
    working_dir: /usr/src/app
    volumes:
     - ./:/usr/src/app
    environment: 
     PORT: 3001
    command: sh -c "cd react-sample && yarn start"
    ports:
     - "3001:3001"

  reverse-proxy:
    image: nginx:alpine
    container_name: 'reverse-proxy-nginx'
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  grafana:
    image: grafana/grafana:latest
    container_name: BI-grafana
    ports: 
      - 3000:3000
